@startuml
title Sequence Diagram: Change Password

actor Customer #lightblue

autonumber

Customer -> ChangePassword: Forgets passcode
activate ChangePassword

ChangePassword -> ChangePassword: Wants to change

ChangePassword -> ChangePassword: Chooses familiar passcode

alt Password is already in use
    ChangePassword -> ChangePassword: Password is already your current password
else
    ChangePassword --> Customer: Enter New Passcode
end

deactivate ChangePassword

@enduml
